require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SuggestedLessonsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # SuggestedLesson. As you add validations to SuggestedLesson, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SuggestedLessonsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all suggested_lessons as @suggested_lessons" do
      suggested_lesson = SuggestedLesson.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:suggested_lessons)).to eq([suggested_lesson])
    end
  end

  describe "GET #show" do
    it "assigns the requested suggested_lesson as @suggested_lesson" do
      suggested_lesson = SuggestedLesson.create! valid_attributes
      get :show, {:id => suggested_lesson.to_param}, valid_session
      expect(assigns(:suggested_lesson)).to eq(suggested_lesson)
    end
  end

  describe "GET #new" do
    it "assigns a new suggested_lesson as @suggested_lesson" do
      get :new, {}, valid_session
      expect(assigns(:suggested_lesson)).to be_a_new(SuggestedLesson)
    end
  end

  describe "GET #edit" do
    it "assigns the requested suggested_lesson as @suggested_lesson" do
      suggested_lesson = SuggestedLesson.create! valid_attributes
      get :edit, {:id => suggested_lesson.to_param}, valid_session
      expect(assigns(:suggested_lesson)).to eq(suggested_lesson)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new SuggestedLesson" do
        expect {
          post :create, {:suggested_lesson => valid_attributes}, valid_session
        }.to change(SuggestedLesson, :count).by(1)
      end

      it "assigns a newly created suggested_lesson as @suggested_lesson" do
        post :create, {:suggested_lesson => valid_attributes}, valid_session
        expect(assigns(:suggested_lesson)).to be_a(SuggestedLesson)
        expect(assigns(:suggested_lesson)).to be_persisted
      end

      it "redirects to the created suggested_lesson" do
        post :create, {:suggested_lesson => valid_attributes}, valid_session
        expect(response).to redirect_to(SuggestedLesson.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved suggested_lesson as @suggested_lesson" do
        post :create, {:suggested_lesson => invalid_attributes}, valid_session
        expect(assigns(:suggested_lesson)).to be_a_new(SuggestedLesson)
      end

      it "re-renders the 'new' template" do
        post :create, {:suggested_lesson => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested suggested_lesson" do
        suggested_lesson = SuggestedLesson.create! valid_attributes
        put :update, {:id => suggested_lesson.to_param, :suggested_lesson => new_attributes}, valid_session
        suggested_lesson.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested suggested_lesson as @suggested_lesson" do
        suggested_lesson = SuggestedLesson.create! valid_attributes
        put :update, {:id => suggested_lesson.to_param, :suggested_lesson => valid_attributes}, valid_session
        expect(assigns(:suggested_lesson)).to eq(suggested_lesson)
      end

      it "redirects to the suggested_lesson" do
        suggested_lesson = SuggestedLesson.create! valid_attributes
        put :update, {:id => suggested_lesson.to_param, :suggested_lesson => valid_attributes}, valid_session
        expect(response).to redirect_to(suggested_lesson)
      end
    end

    context "with invalid params" do
      it "assigns the suggested_lesson as @suggested_lesson" do
        suggested_lesson = SuggestedLesson.create! valid_attributes
        put :update, {:id => suggested_lesson.to_param, :suggested_lesson => invalid_attributes}, valid_session
        expect(assigns(:suggested_lesson)).to eq(suggested_lesson)
      end

      it "re-renders the 'edit' template" do
        suggested_lesson = SuggestedLesson.create! valid_attributes
        put :update, {:id => suggested_lesson.to_param, :suggested_lesson => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested suggested_lesson" do
      suggested_lesson = SuggestedLesson.create! valid_attributes
      expect {
        delete :destroy, {:id => suggested_lesson.to_param}, valid_session
      }.to change(SuggestedLesson, :count).by(-1)
    end

    it "redirects to the suggested_lessons list" do
      suggested_lesson = SuggestedLesson.create! valid_attributes
      delete :destroy, {:id => suggested_lesson.to_param}, valid_session
      expect(response).to redirect_to(suggested_lessons_url)
    end
  end

end
